### ISSUE TITLE
OnLoadMore is being called for the first time sample app opens

### ISSUE THREAD

**Issue by mori-honest** [NoNews/NoPaginate#1]

**Comment by NoNews** [comment]
Hi @mori-honest, thank you for this issue.
I will fix it in `0.4.4` which I plan to release at the end of the week.

**Comment by mori-honest** [comment]
Thanks for your help! I appreciate that!

**Comment by NoNews** [comment]
@mori-honest
I can't catch that behavior. (API 21 and 23)
Tell me please version API and phone model

**Comment by NoNews** [comment]
@mori-honest 
Maybe problem with method `setLoadingTriggerThreshold`?
Can you try `setLoadingTriggerThreshold(0)` in your `PaginateBuilder`?

**How it works:**
Method `setLoadingTriggerThreshold` set the offset from end of the list.
Default offset is 5.
It means that method `onLoadMore` will triggered  when user scrolled to `bottom position - 5` elements.

For now, the only thing that comes to mind is to put the `loadingTriggerThreshold` in the default library to 0

**Comment by NoNews** [comment]
@mori-honest 
0.4.4 released, don't forget about [changelog](https://github.com/NoNews/NoPaginate/releases)
