### ISSUE TITLE
Retrofit implementation Needed

### ISSUE THREAD

**Issue by AhmadullahSaikat** [NoNews/NoPaginate#12]
Very good step.
You need to implement your sample app code with Retrofit.

**Comment by rupinderjeet** [comment]
How does retrofit effect this library?

**Comment by NoNews** [comment]
@AhmadullahSaikat You can see mock http request here:
https://github.com/NoNews/NoPaginate/blob/master/sample/src/main/java/ru/alexbykov/pagination/presenters/MainActivityPresenter.java

Looks like retrofit callbacks. 
All you need is http request in onLoadMore();
