### ISSUE TITLE
Custom view when there is not more items to show

### ISSUE THREAD

**Issue by MitchDroid** [NoNews/NoPaginate#14]
Hi @NoNews  its me again.. lol.

Just one question,:

is it possible to show a custom view when there is not more items to show.?..I mean something like "There is not more items to show for the moment"

PD: something like the custom error view.

Regards.

**Comment by NoNews** [comment]
Hi @MitchDroid 

I think it's really specific case for this library. And I think. it's not a good UX.
But, if it really necessary, you can use custom ViewHolders for this situation
