### ISSUE TITLE
OnLoadMore is being called twice at the initilization

### ISSUE THREAD

**Issue by Mystogun** [NoNews/NoPaginate#3]

**Comment by NoNews** [comment]
Hi @Mystogun, сan you show the code of your `Fragment` or `Activity`?

**Comment by NoNews** [comment]
#1

**Comment by Mystogun** [comment]
I'm loading 20 items per request to a recycler and the OnLoadMore is being called twice

here's the initialization
`
paginate = Paginate.with(binding.list, this)
                .setLoadingTriggerThreshold(2)
                with(recyclerView)
                .setOnLoadMoreListener(new OnLoadMoreListener() {
                    @Override
                    public void onLoadMore() {
                        loadPosts();
                    }
                })
                .build();
`

and her is the loadPosts() method

` private void loadPosts() {
            Call<GetRecentResponse> call = retrofit.create(PostsInterface.class).getRecent(page, offset);
            call.enqueue(new Callback<GetRecentResponse>() {
                @Override
                public void onResponse(Call<GetRecentResponse> call, Response<GetRecentResponse> response) {
                    binding.loading.setVisibility(View.GONE);
                    binding.textStatus.setVisibility(View.GONE);
                    binding.status.setVisibility(View.GONE);
                    isLoading = false;
                    if (!reachedBottom) {
                        if (response.body() != null) {
                            if (response.body().getRecent() != null) {
                                if (response.body().getRecent().size() > 0) {
                                    posts = response.body().getRecent();
                                    adapter.addItems(posts);
                                    page++;
                                } else if (response.body().getRecent().size() == 0) {
                                    reachedBottom = true;
                                }
                            }
                        }
                    }
                 }

                @Override
                public void onFailure(Call<GetRecentResponse> call, Throwable t) {
                    binding.loading.setVisibility(View.GONE);
                    binding.status.setImageResource(R.drawable.error2x);
                    binding.textStatus.setText(t.getLocalizedMessage());
                    isLoading = false;
                }
            });
}
`

**Comment by NoNews** [comment]
@Mystogun Can you try `setLoadingTriggerThreshold(0)` in your builder? I described  behavior here  #1

**Comment by NoNews** [comment]
@Mystogun And, show your gradle dependencies. 
I think you use library [Paginate](https://github.com/MarkoMilos/Paginate).
But this repository belongs to the library [NoPaginate](https://github.com/NoNews/NoPaginate)

In your case in would be like this:


`implementation 'ru.alexbykov:nopaginate:0.4.4'` in gradle

  ```
Paginate paginate = new PaginateBuilder()
                .with(recyclerView)
                .setOnLoadMoreListener(new OnLoadMoreListener() {
                    @Override
                    public void onLoadMore() {
                        //http or db request here
                    }
                })
                .build();
```
That's it.

**Comment by Mystogun** [comment]
@NoNews, OK I'll try using ```setLoadingTriggerThreshold(0)```

yeah, I was using [Paginate](https://github.com/MarkoMilos/Paginate) before, then there was a lot of bugs with it so I changed to yours [NoPaginate](https://github.com/NoNews/NoPaginate)
because it offered more features.

**Comment by Mystogun** [comment]
The ```setLoadingTriggerThreshold(0)``` worked fine, Thanks a lot

**Comment by NoNews** [comment]
@Mystogun  I am glad to help!

Note, in the version `0.4.4`  `setLoadingTriggerThreshold(0)` is default behavior. 
It means, that install manually `setLoadingTriggerThreshold(0)` not necessary.
