### ISSUE TITLE
OnLoadMore called two times for lesser data 

### ISSUE THREAD

**Issue by aqibgatoo** [NoNews/NoPaginate#4]
Firstly thanks for the great library i was able to remove a lot of boilerplate from my code.👍

My api call is supposed to load **10 items per page** but since the data coming from first call is only **4 items** this results in `onLoadMore `being called one more time.

**Comment by NoNews** [comment]
Hi @aqibgatoo, I'm glad that you like the library!

Try to call method `paginate.setNoMoreItems(true)`, before adding items to the adapter.
It would be like that:

```
void onSuccess(Response<List<YourModel>> response){
List<YourModel> items = response.getList();

//Next, you need to find out if there are more data to load from the backend
//Usually the backend provides information about this in the response:

if (response.isNoMoreItemsToLoad())
//if true - method onLoadMore will not to call
paginate.setNoMoreItems(true)
}
paginate.addItems(items);

```

But, if backend have no information in the response, you can find it manually:

```
void onSuccess(Response<List<YourModel>> response){
List<YourModel> items = response.getList();

if (items.isEmpty()||items.size<Constants.LIMIT){
paginate.setNoMoreItems(true)
}
paginate.addItems(items);
}
```

**Comment by aqibgatoo** [comment]
Great!! thanks for the response and giving the solution. I will manually check since my backend doesn't supply the information for the remaining data.
