### ISSUE TITLE
Add an item to show that Adapter is empty

### ISSUE THREAD

**Issue by rupinderjeet** [NoNews/NoPaginate#5]
Can you add an Item in adapter to show that Adapter is empty? View can notify Paginate that the item-count has changed. If user enables this Empty Item and item-count reaches 0, you can show this item.

I use a layout to show Empty Adapter, but it is shown on top of RecyclerView in FrameLayout. I want to have it in Adapter, and be able to turn it on/off manually.

Thanks. Your library works amazingly even without this feature.

![layout-2018-03-16-174829](https://user-images.githubusercontent.com/14011726/37520292-75db69f4-2942-11e8-829e-ab69779f965d.png)

**Comment by NoNews** [comment]
Hi @rupinderjeet, thanks for this issue. 
Good idea, but I'm not sure that everyone will need it.

Need to think about this moment, I will try to give feedback after the weekend
@amnesiak   what do you think?

**Comment by amnesiak** [comment]
I think that such a function should be in the standard RecyclerView, but it is not there. I think it will be convenient for everyone. When we use MVP-pattern, we will no longer have a function like showEmptyList(), this logic can be encapsulated in the adapter

**Comment by NoNews** [comment]
@rupinderjeet 
Yep, you can make `ViewHolder` for this, and take it into base adapter.

It would be like this: 

**New method in BaseRecyclerViewAdapter:**

```Java
  public void showEmptyItem() {
        items.clear();
        mIsShowEmptyItem = true;
        notifyDataSetChanged();
    }
```

**getItemViewType():**
```Java
public int getItemViewType(){
...........
   if (mIsShowEmptyItem){
        return EMPTY_ITEM;
   }
...........
}
```

**Some Activity/Fragment logic: (just example)**

```Java
 public void showData(List<Cat> items) {
        if (items.isEmpty()) {
            adapter.showEmptyItem();
        } else {
            adapter.addItems(items);
        }
    }

```
To your definition I would also add that `RecyclerView` adapter is responsible for the binding of each element in the `RecyclerView`.

I think that good idea, but not for NoPaginate. 

I will try to implement this function in this library:
https://github.com/NoNews/NoRecyclerViewAdapter

While it's in development mode
